export const staffData = [{
    "id": "Skills",
    "color": "hsl(20, 70%, 50%)",
    "data": [
      { "x": "Project Lead", "y": 356 },
      { "x": "Software Engineer", "y": 124 },
      { "x": "Product Manager", "y": 34 },
      { "x": "UX Designer", "y": 321 },
      { "x": "QA Tester", "y": 191 },
      { "x": "DevOps Engineer", "y": 34 },
      { "x": "Data Scientist", "y": 79 },
      { "x": "Business Analyst", "y": 89 },
      { "x": "Marketing Manager", "y": 215 },
      { "x": "Sales Manager", "y": 143 },
      { "x": "HR Manager", "y": 167 },
      { "x": "Security Analyst", "y": 128 }
    ]
  }]
  
  export const projectData = [{
    "id": "Projects",
    "color": "hsl(220, 70%, 50%)",
    "data": [
      { "x": "Website Development", "y": 145 },
      { "x": "Mobile App Development", "y": 134 },
      { "x": "Data Analysis", "y": 128 },
      { "x": "Cloud Migration", "y": 115 },
      { "x": "Cybersecurity", "y": 120 },
      { "x": "IT Support", "y": 170 },
      { "x": "SEO Optimization", "y": 135 },
      { "x": "Digital Marketing", "y": 140 },
      { "x": "Product Design", "y": 118 },
      { "x": "UI/UX Design", "y": 135 },
      { "x": "Business Consulting", "y": 122 },
      { "x": "Project Management", "y": 133 }
    ]
  }]
  
  export const saleDate = [{
    "id": "Sales",
    "color": "hsl(140, 70%, 50%)",
    "data": [
      { "x": "Software Licenses", "y": 50000 },
      { "x": "Consulting Services", "y": 35000 },
      { "x": "Maintenance Contracts", "y": 20000 },
      { "x": "Cloud Services", "y": 45000 },
      { "x": "Training Programs", "y": 15000 },
      { "x": "Custom Development", "y": 30000 },
      { "x": "Hardware Sales", "y": 25000 },
      { "x": "Subscription Services", "y": 40000 },
      { "x": "E-commerce Solutions", "y": 22000 },
      { "x": "Digital Marketing", "y": 28000 },
      { "x": "Analytics Services", "y": 18000 },
      { "x": "Security Solutions", "y": 30000 }
    ]
  }]
  
  export const gridData = [
    {
      id: 1,
      projectName: 'Website Development',
      data: '2023-05-31',
      price: '5000',
      stats: 'In Progress',
      gmail: 'project1@example.com',
      customer: { name: 'John Doe', src: 'https://cdn.shopify.com/s/files/1/0289/5858/9027/files/2_c217860d-ec91-4984-920b-c23a538c076b.png?v=1579072690' },
    },
    {
      id: 2,
      projectName: 'Mobile App Development',
      data: '2023-06-15',
      price: '8000',
      stats: 'Completed',
      gmail: 'project2@example.com',
      customer: { name: 'Jane Smith', src: 'https://cdn.shopify.com/s/files/1/0662/3537/files/HairstylesForRoundFacesMenFauxHawk.png?v=1678672612' },
    },
    {
      id: 3,
      projectName: 'Data Analysis',
      data: '2023-07-10',
      price: '4000',
      stats: 'In Progress',
      gmail: 'project3@example.com',
      customer: { name: 'Alice Johnson', src: 'https://content.latest-hairstyles.com/wp-content/uploads/short-wavy-balayage-bob-round-face.jpg' },
    },
    {
      id: 4,
      projectName: 'Cloud Migration',
      data: '2023-08-05',
      price: '10000',
      stats: 'Not Started',
      gmail: 'project4@example.com',
      customer: { name: 'Bob Brown', src: 'https://i.pinimg.com/564x/3c/49/2c/3c492c60155dfedb103eaa49d22d8525.jpg' },
    },
    {
      id: 5,
      projectName: 'Cybersecurity',
      data: '2023-09-20',
      price: '7000',
      stats: 'In Progress',
      gmail: 'project5@example.com',
      customer: { name: 'Charlie Green', src: 'https://i2.wp.com/www.hadviser.com/wp-content/uploads/2019/04/1-hairstyle-for-a-round-face-to-look-slim-CYsRbpPDNv-.jpg?resize=1344%2C1344&ssl=1' },
    },
    {
      id: 6,
      projectName: 'IT Support',
      data: '2023-10-01',
      price: '3000',
      stats: 'Completed',
      gmail: 'project6@example.com',
      customer: { name: 'Diana Prince', src: 'https://www.fabmood.com/wp-content/uploads/2021/10/round-face-haircut-9.jpg' },
    },
    {
      id: 7,
      projectName: 'SEO Optimization',
      data: '2023-11-12',
      price: '2000',
      stats: 'Not Started',
      gmail: 'project7@example.com',
      customer: { name: 'Ethan Hunt', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxBIbBpZYBnza5vF4P6071-o_1pGXdEYrbkw&s' },
    },
    {
      id: 8,
      projectName: 'Digital Marketing',
      data: '2023-12-20',
      price: '4500',
      stats: 'In Progress',
      gmail: 'project8@example.com',
      customer: { name: 'Fiona Apple', src: 'https://www.southernliving.com/thmb/PLSKzaMs1OO1uP9QSMQg78kA-Xk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/bob-blonde-4fb71fc20f0f43b1a32e30f59498d140.jpg' },
    },
    {
      id: 9,
      projectName: 'Product Design',
      data: '2024-01-15',
      price: '6000',
      stats: 'Completed',
      gmail: 'project9@example.com',
      customer: { name: 'George Lucas', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs8kB3i20TFKXxxxoqlvz3S8ahluSgXnsLiGgu75ODz7bFjTwSqbMT38sczqdh3wPRxYs&usqp=CAU' },
    },
    {
      id: 10,
      projectName: 'UI/UX Design',
      data: '2024-02-05',
      price: '5500',
      stats: 'Not Started',
      gmail: 'project10@example.com',
      customer: { name: 'Harry Potter', src: 'https://i.pinimg.com/564x/79/4b/1c/794b1ce79bc785807aa6c25e1d349662.jpg' },
    },
    {
      id: 11,
      projectName: 'Business Consulting',
      data: '2024-03-20',
      price: '7500',
      stats: 'In Progress',
      gmail: 'project11@example.com',
      customer: { name: 'Isabella Swan', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFkbavrjqUxkmsGRGkg2sZzyfH3uYtG3mh6W4vP6S5fWdOlC-IbEN6W0MDYkoUd99Vx8E&usqp=CAU' },
    },
    {
      id: 12,
      projectName: 'Project Management',
      data: '2024-04-01',
      price: '5000',
      stats: 'Completed',
      gmail: 'project12@example.com',
      customer: { name: 'Jack Sparrow', src: 'https://i.pinimg.com/474x/62/69/5b/62695b2a4b73cf2ca1dc35ec6a1d0ec7.jpg' },
    },
    {
      id: 13,
      projectName: 'Cloud Integration',
      data: '2024-04-18',
      price: '9000',
      stats: 'Not Started',
      gmail: 'project13@example.com',
      customer: { name: 'Kara Danvers', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSe8EA6zhxSSkUxuKHr9BCJBeAO2TTaRM81k0_lsrZSsyyF0nwTMBBuOD2h6BYrbcKeeWM&usqp=CAU' },
    },
    {
      id: 14,
      projectName: 'Cybersecurity Audit',
      data: '2024-05-10',
      price: '9500',
      stats: 'In Progress',
      gmail: 'project14@example.com',
      customer: { name: 'Luke Skywalker', src: 'https://i.pinimg.com/564x/7f/d6/cb/7fd6cb9baa3654f97b305e285ac8b7d7.jpg' },
    },
    {
      id: 15,
      projectName: 'Maintenance',
      data: '2024-06-01',
      price: '12000',
      stats: 'Completed',
      gmail: 'project15@example.com',
      customer: { name: 'Mary Jane', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCPrftGOrwU0nv6LxqjYEq5njLStQ1tzIELY7ecmhHqewlAvzkIGikTaAoiE1yAcP9www&usqp=CAU' },
    },
    {
      id: 16,
      projectName: 'Server Setup',
      data: '2024-06-20',
      price: '8000',
      stats: 'Not Started',
      gmail: 'project16@example.com',
      customer: { name: 'Nancy Drew', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-NsT0NsrxuPQvPZUzG2aZtyjr1YIJllDOdMrRkZfEdoQpR1JWbYlC3-MP4TOiqvN1pm0&usqp=CAU' },
    },
    {
      id: 17,
      projectName: 'System Upgrade',
      data: '2024-07-15',
      price: '7000',
      stats: 'In Progress',
      gmail: 'project17@example.com',
      customer: { name: 'Oscar Wilde', src: 'https://external-preview.redd.it/XKrEz0r7Aa_JCNg_jZbwiOdtJ0aelPgu3QmKJgVxdT0.jpg?auto=webp&s=2647a73be98466a9669df6ce8678e8595c3702d6' },
    },
    {
      id: 18,
      projectName: 'Application Testing',
      data: '2024-08-01',
      price: '3500',
      stats: 'Completed',
      gmail: 'project18@example.com',
      customer: { name: 'Paul Walker', src: 'https://i.pinimg.com/550x/41/c5/e3/41c5e37e6b1cf2ba75949a66fab89f6e.jpg' },
    },
    {
      id: 19,
      projectName: 'Training & Development',
      data: '2024-09-10',
      price: '6500',
      stats: 'Not Started',
      gmail: 'project19@example.com',
      customer: { name: 'Quentin Tarantino', src: 'https://i.pinimg.com/originals/7f/20/db/7f20db27d7ce5e99f785be9d5813d0a7.jpg' },
    },
    {
      id: 20,
      projectName: 'Vendor Management',
      data: '2024-10-05',
      price: '5000',
      stats: 'In Progress',
      gmail: 'project20@example.com',
      customer: { name: 'Rachel Green', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqu1b1L-2qRw2MPYYZTtUPLjdCUzeirzagb1QtF7tA5q9wC-SlXdEkE2s06emzz_LednY&usqp=CAU' },
    },
  ]
  
  export const sideCardData = {
    first: [
      { name: 'David Williams', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSe8EA6zhxSSkUxuKHr9BCJBeAO2TTaRM81k0_lsrZSsyyF0nwTMBBuOD2h6BYrbcKeeWM&usqp=CAU' },
      { name: 'Charlie Johnson', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqu1b1L-2qRw2MPYYZTtUPLjdCUzeirzagb1QtF7tA5q9wC-SlXdEkE2s06emzz_LednY&usqp=CAU' },
      { name: 'Alice Smith', src: '' },
      { name: 'Bob Brown', src: 'https://i.pinimg.com/550x/41/c5/e3/41c5e37e6b1cf2ba75949a66fab89f6e.jpg' },
    ],
    second: [
      { name: 'David Williams', src: 'https://external-preview.redd.it/XKrEz0r7Aa_JCNg_jZbwiOdtJ0aelPgu3QmKJgVxdT0.jpg?auto=webp&s=2647a73be98466a9669df6ce8678e8595c3702d6' },
      { name: 'Charlie Johnson', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-NsT0NsrxuPQvPZUzG2aZtyjr1YIJllDOdMrRkZfEdoQpR1JWbYlC3-MP4TOiqvN1pm0&usqp=CAU' },
      { name: 'Alice Smith', src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCPrftGOrwU0nv6LxqjYEq5njLStQ1tzIELY7ecmhHqewlAvzkIGikTaAoiE1yAcP9www&usqp=CAU' },
      { name: 'Bob Brown', src: 'https://i.pinimg.com/564x/7f/d6/cb/7fd6cb9baa3654f97b305e285ac8b7d7.jpg' },
    ],
  };
  
  export const feedbackData = [
    {
      name: 'Remy Sharp',
      rating: 4,
      orderDate: '19/05/2013',
      message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et justo non sapien dapibus dapibus. In hac habitasse platea dictumst.",
    },
    {
      name: 'Alice Johnson',
      rating: 5,
      orderDate: '23/11/2020',
      message: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque in ipsum id orci porta dapibus.",
    },
    {
      name: 'John Doe',
      rating: 3,
      orderDate: '15/01/2018',
      message: "Sed porttitor lectus nibh. Nulla porttitor accumsan tincidunt. Donec sollicitudin molestie malesuada.",
    },
    {
      name: 'Jane Smith',
      rating: 2,
      orderDate: '01/04/2022',
      message: "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.",
    },
    {
      name: 'Michael Brown',
      rating: 4,
      orderDate: '12/08/2019',
      message: "Proin eget tortor risus. Vivamus suscipit tortor eget felis porttitor volutpat. Nulla quis lorem ut libero malesuada feugiat.",
    },
    {
      name: 'Emily Davis',
      rating: 5,
      orderDate: '30/09/2017',
      message: "Pellentesque in ipsum id orci porta dapibus. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    },
    {
      name: 'Daniel Wilson',
      rating: 3,
      orderDate: '21/11/2016',
      message: "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Nulla quis lorem ut libero malesuada feugiat. Donec sollicitudin molestie malesuada.",
    },
    {
      name: 'Sophia Martinez',
      rating: 4,
      orderDate: '11/03/2021',
      message: "Quisque velit nisi, pretium ut lacinia in, elementum id enim. Curabitur aliquet quam id dui posuere blandit.",
    },
    {
      name: 'James Anderson',
      rating: 2,
      orderDate: '27/05/2015',
      message: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.",
    },
    {
      name: 'Isabella Thomas',
      rating: 5,
      orderDate: '04/07/2018',
      message: "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada.",
    }
  ];
  
  export const trafficData = [
    { "id": "Search Engines ", "label": "Search Engines", "value": 108797, "color": "hsl(138, 70%, 50%)" },
    { "id": "Direct Traffic", "label": "Direct Traffic", "value": 39351, "color": "hsl(265, 70%, 50%)" },
    { "id": "Referring Sites", "label": "Referring Sites", "value": 27668, "color": "hsl(188, 70%, 50%)" },
  ]